In [0]:
import pandas as pd

In [0]:
#reading data from csv file using variable df
df=pd.read_csv('com.csv')

In [0]:
#Reading data from a csv file
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
Name          6 non-null object
Department    4 non-null object
Manager       4 non-null object
Salary        6 non-null int64
dtypes: int64(1), object(3)
memory usage: 272.0+ bytes

In [0]:
# to read all data
df

            Name Department      Manager  Salary
0     Robin Hood        NaN          NaN     200
1  Arsene Wenger        Bar   Friar Tuck      50
2     Friar Tuck        Foo   Robin Hood     100
3    Little John        Foo   Robin Hood     100
4  Sam Allardyce        NaN          NaN     250
5  Dimi Berbatov        Foo  Little John      50

In [0]:
#for top 3 rows
df.head(3)

            Name Department     Manager  Salary
0     Robin Hood        NaN         NaN     200
1  Arsene Wenger        Bar  Friar Tuck      50
2     Friar Tuck        Foo  Robin Hood     100

In [0]:
# particular coloumn
df['Name']

0       Robin Hood
1    Arsene Wenger
2       Friar Tuck
3      Little John
4    Sam Allardyce
5    Dimi Berbatov
Name: Name, dtype: object

In [0]:
# select rows and coloumns, syntax inside braces is same as numpy
df.iloc[0:,[0,3]]

            Name  Salary
0     Robin Hood     200
1  Arsene Wenger      50
2     Friar Tuck     100
3    Little John     100
4  Sam Allardyce     250
5  Dimi Berbatov      50

In [0]:
#salary 
df['Salary']

0    200
1     50
2    100
3    100
4    250
5     50
Name: Salary, dtype: int64

In [0]:
#maximum salary
df['Salary'].max()

250

In [0]:
#minimum salary
df['Salary'].min()

50

In [0]:
# sum of salary
df['Salary'].sum()

750

In [0]:
type(df)

pandas.core.frame.DataFrame